#!/bin/sh -e

cd /etc/ssh

[ -f "ssh_host_dsa_key" ] \
|| ssh-keygen -b 1024 -t dsa -N "" -C "dsa host key" -f ssh_host_dsa_key > /dev/null 2>&1

[ -f "ssh_host_ecdsa_key" ] \
|| ssh-keygen -b 256 -t ecdsa -N "" -C "ecdsa host key" -f ssh_host_ecdsa_key > /dev/null 2>&1

[ -f "ssh_host_ed25519_key" ] \
|| ssh-keygen -b 256 -t ed25519 -N "" -C "ed25519 host key" -f ssh_host_ed25519_key > /dev/null 2>&1

[ -f "ssh_host_rsa_key" ] \
|| ssh-keygen -b 1024 -t rsa -N "" -C "rsa host key" -f ssh_host_rsa_key > /dev/null 2>&1

[ -f "/root/.ssh/id_rsa" ] \
|| ssh-keygen -b 1024 -N "" -C "root@gitolite" -f /root/.ssh/id_rsa > /dev/null 2>&1
