#!/bin/sh -e

PORT_DIR=/mnt/_
SSH_DIR=/root/.ssh
GIT_DIR=/mnt/git

cd "$SSH_DIR"

[ ! -f "$PORT_DIR/id_rsa" -o ! -f "$PORT_DIR/id_rsa.pub" ] || {
    cp -f "$PORT_DIR/id_rsa" .
    cp -f "$PORT_DIR/id_rsa.pub" .
    chmod 0600 id_rsa
    chmod 0644 id_rsa.pub
    IMPORTED=1
}

cd "$PORT_DIR"

[ -n "$IMPORTED" ] || {
    cp -f "$SSH_DIR/id_rsa" .
    cp -f "$SSH_DIR/id_rsa.pub" .
    chmod 0400 id_rsa*
}

cd "$GIT_DIR"

[ ! -f "projects.list" -o -n "$IMPORTED" ] || {
    BACKUP_DIR="./-backup-"`date +"%Y%m%dT%H%M%S"`
    mkdir "$BACKUP_DIR"
    for ii in .* *; do
        [ "x." != "x$ii" ] || continue
        [ "x.." != "x$ii" ] || continue
        [ "x-backup-" != "x${ii:0:8}" ] || continue
        mv "$ii" "$BACKUP_DIR/"
    done
    mkdir repositories
    for ii in "$BACKUP_DIR/repositories/"*; do
        jj=`basename "$ii"`
        [ "xgitolite-admin.git" != "x$jj" ] || continue
        mv "$ii" repositories/
    done
    find -L repositories -type l -delete
}

chown -hR git:nobody .

[ -f "projects.list" ] || {
    cp -f "$SSH_DIR/id_rsa.pub" /tmp/root.pub
    chown git /tmp/root.pub
    su - git -c "/srv/gitolite/gitolite setup -pk /tmp/root.pub -m 'initialized.' > /dev/null 2>&1"
    rm -f /tmp/root.pub
}

#chmod -R 0600 .
#find . -type d -exec chmod 0700 {} \;
#find .gitolite/hooks -type f -exec chmod 0700 {} \;
