#!/bin/sh -e

cd /mnt/git

[ -f "projects.list" ] && {
  [ ! -f docker.key ] || {
    cp -f docker.key /root/.ssh/id_rsa
    chmod 0600 /root/.ssh/id_rsa
    rm -f /root/.ssh/id_rsa.pub
  }
} || {
  cp -f /root/.ssh/id_rsa.pub root.pub
  cp -f /root/.ssh/id_rsa docker.key
  su - git -c "/srv/gitolite/gitolite setup -pk root.pub -m 'initialized.' > /dev/null 2>&1"
}

rm -f root.pub
