#!/bin/sh -e

[ 0 -lt $# ] || {
  for ii in /srv/up.d/*; do
    sh -e "$ii" 3>> /var/git/docker.log
    RCD=$?
    [ 0 -eq $RCD ] || exit $RCD
  done
  set -- /usr/sbin/sshd -4D
}

exec "$@"

# vi:sw=2
