#!/bin/sh -e

_echo() {
  echo `date +"%Y-%m-%d %H:%I:%S"`"$@" >&3
}

su - git -c "test -O /var/git" || chown -R git:docker /var/git
cd /var/git

[ -f "projects.list" ] && {
  [ ! -f docker.key ] || cp -f docker.key /root/.ssh/id_rsa
} || {
  cp -f /root/.ssh/id_rsa.pub root.pub
  cp -f /root/.ssh/id_rsa docker.key
  su - git -c "/srv/gitolite/gitolite setup -pk root.pub -m 'initialized.'"
  _echo " initialized."
}

rm -f root.pub

# vi:ft=sh:sw=2
